- .github/workflows/deploy-front.yml
- deploy.sh
- actions/setup-node에서 npm 캐시 제거
- pnpm/action-setup 추가
- pnpm 캐시 설정 추가
- 의존성 설치를 pnpm install --frozen-lockfile로 변경
- 빌드 명령어를 pnpm build로 변경
- 배포 스크립트에서 pnpm 설치 및 사용하도록 수정
> fix: GitHub Actions 워크플로우를 pnpm 사용하도록 수정

- src/app/deploy-test/page.tsx
- src/app/home/layout.tsx
- src/app/home/page.tsx
- src/app/stock/[code]/page.tsx
- src/app/home/layout.tsx 주석 해제하여 React 컴포넌트 export
- src/app/home/page.tsx에서 window.location.href를 useRouter로 변경
- src/app/stock/[code]/page.tsx에서 컴포넌트 import 경로 수정
- deploy.sh에서 pnpm 사용하도록 복원 (스왑 메모리 추가로 메모리 문제 해결)
- 배포 테스트 페이지 추가
> fix: 빌드 오류 해결 및 배포 스크립트 개선

- src/app/layout.tsx
- src/components/conditional-layout.tsx
- src/hooks/useNotification.ts
- 프론트엔드 SSE 알림 기능 구현 및 전역 toast 연동
---
- useNotification hook 작성 및 SSE 연결 처리
- 기존 커스텀 toast 시스템과 연동 
- ConditionalLayout에 useNotification 통합하여 모든 페이지에서 알림 받을 수 있도록 적용
- layout.tsx 구조 개선 및 Toaster 전역 설정
- memberId는 현재 임시값(1) 사용, 추후 로그인 연동 시 수정 예정
---
- Close #6
---
---
- 추후 로그인 연동 완료 후 memberId를 전역 상태에서 불러오도록 수정 필요
> Feat : SSE 알림 hook 추가 및 전역 toast 알림 연동

- src/app/login/page.tsx
- src/components/top-navigation.tsx
로그인 화면 UI 구현
- 로그인 화면 UI 구현
Close #11 
없음
> Feat : 로그인 화면 UI 구현

- package.json
- pnpm-lock.yaml
- src/app/login/page.tsx
- src/app/signup/accountRegister/page.tsx
- src/app/signup/page.tsx
- src/app/signup/phoneNumber/page.tsx
- src/app/signup/userAccount/page.tsx
- src/components/top-navigation.tsx
회원가입 화면 UI 구현
회원가입 화면 UI 구현
- 이름 입력 UI 구현
- 휴대폰 본인인증 UI 구현
- 계정 정보 등록 UI 구현
- 계좌 정보 등록 UI 구현
📌 관련 이슈
Close #12 
없음
> Feat : 회원가입 UI 구현

- .github/workflows/deploy-front.yml
> fix: CI/CD 개선사항 - 배포 스크립트 수정 최종

- src/app/stock/[code]/page.tsx
> Fix stock price display format and currency formatting

- src/app/stock/[code]/page.tsx
- src/components/key-stats.tsx
- src/components/news-section.tsx
- src/components/stock-header.tsx
> refactor: stock detail page 분리 및 컴포넌트화, 차트 제거

- pnpm-lock.yaml
- src/app/login/page.tsx
- src/app/signup/accountRegister/page.tsx
- src/app/signup/page.tsx
- src/app/signup/phoneNumber/page.tsx
- src/app/signup/userAccount/page.tsx
- src/stores/signupStore.ts
- 회원가입 백엔드 API 연결
---
- 이름 입력 백엔드 API 연결
- 계정 정보 입력 백엔드 API 연결
- 계좌 정보 입력 백엔드 API 연결
- 본인 인증 백엔드 API 연결
---
- Close #61 
---
---
> Feat [: 회원가입 API를 연결한다

- .github/workflows/deploy-front.yml
> hotfix:remove .env from deploy-from.yml

- deploy.sh
- ecosystem.config.js
> hotfix:add pnpm build when deploy

- src/app/disclosure/[id]/page.tsx
- src/app/home/page.tsx
- src/components/ui/info-tabs.tsx
- 공시 상세페이지 UI를 구현하고 백엔드와 통신한다
---
- 공시 상세페이지 UI를 구현
- 백엔드와 통신
---
- Close #82 
- Close #78 
---
---
> Feat : 공시 상세페이지 UI를 구현하고 백엔드와 통신한다

- deploy.sh
- ecosystem.config.js
- src/app/deploy-test/page.tsx
- ecosystem.config.js: NEXT_PUBLIC_BACK_API_URL을 /api/v1로 설정
- deploy-test/page.tsx: 하드코딩된 IP 주소를 상대 경로로 변경
- deploy.sh: 배포 완료 메시지 URL을 https://sumearly.store로 업데이트
---
- 주요 변경사항 리스트
---
---
---
> fix: API URL을 상대 경로로 변경하여 mixed-content 에러 해결

- src/components/key-stats.tsx
- src/components/news-section.tsx
- stock-chart.tsx: /api/stock-data 경로로 수정하여 프론트엔드 API 라우트 사용
- nginx 설정에 맞춰 프론트엔드 API와 백엔드 API 경로 분리 완료
---
- 주요 변경사항 리스트
---
---
---
> fix: stock-chart API 경로를 nginx 설정에 맞게 수정

- src/app/scrap/page.tsx
스크랩 페이지 수정
---
- 주요 변경사항 리스트
스크랩 페이지 수정
---
---
---
> Hotfix: 스크랩페이지 수정

- next.config.mjs
- src/components/bottom-navigation.tsx
- next.config.mjs: API 라우팅 패턴을 /api/v1/:path*로 변경하여 내장 API Route와 분리
- bottom-navigation.tsx: z-index 추가로 네비게이션 레이어 우선순위 개선
---
- 주요 변경사항 리스트
---
---
---
> feat: API 라우팅 설정 개선 및 UI 수정

- src/app/calendar/CalendarClient.tsx
- src/app/disclosure/[id]/page.tsx
- 날짜 셀을 정사각형 비율로 수정 (aspect-square)
- 요일 헤더도 정사각형 비율로 조정
- 고정 높이 제거로 자연스러운 비율 유지
- 모바일과 데스크톱에서 일관된 정사각형 레이아웃
---
- 주요 변경사항 리스트
---
---
---
> feat: 달력 UI 개선 - 정사각형 날짜 셀 및 반응형 레이아웃

- src/app/scrap/page.tsx
- src/components/scrap/ScrapCardViewer.tsx
- src/components/scrap/ScrapStockList.tsx
- src/components/scrap/ScrapStockSelector.tsx
- src/components/scrap/TrebleSelector.tsx
- src/components/ui/DualSelector.tsx
- src/components/ui/ScrapGroupDialog.tsx
- src/components/ui/StockLogo.tsx
스크랩 기능 추가
---
- 주요 변경사항 리스트
스크랩 기능 추가
---
---
---
> Feat/스크랩 기능 추가

- src/components/scrap/ScrapCardViewer.tsx
- src/components/ui/CardViewer.tsx
CardViewer Reactive
---
- 주요 변경사항 리스트
CardViewer Reactive
---
---
---
> Feat: CardViewer Reactive

- src/app/profile/edit-investment/page.tsx
마이페이지-저장하기-이슈 해결
---
- 주요 변경사항 리스트
마이페이지-저장하기-이슈 해결
---
---
---
> Feat: 마이페이지-저장하기-이슈 해결

- src/app/disclosure/[id]/page.tsx
- src/app/home/page.tsx
- src/app/signup/accountRegister/page.tsx
- src/app/signup/page.tsx
- src/app/signup/phoneNumber/page.tsx
- src/app/signup/userAccount/page.tsx
- src/components/ui/info-tabs.tsx
- UI 디테일 잡기
---
- 회원가입 오른쪽 아이콘 제거
- 어닝콜 라우팅 제거
- 미국 증시 뉴스 야후 finance 라우팅
---
- Close #122 
---
---
> Feat : UI 디테일을 잡는다
